- .github/workflows/ci.yml
> 21480 Enable CI

- .github/workflows/ci.yml
Added section to ci.yml to also Publish the search-cli image to DockerHub
> 22702 Release search-cli Image to Docker Hub

- .github/workflows/release-es-init-container.yml
Added manual trigger for es-init-container image
> 22688 Release es-init-container Image to Docker Hub

- pom.xml
> 23390 Update SpringBoot

- search-messaging/src/main/java/ca/gc/aafc/dina/search/messaging/producer/LogBasedMessageProducer.java
- search-messaging/src/main/java/ca/gc/aafc/dina/search/messaging/producer/MessageProducer.java
- search-messaging/src/main/java/ca/gc/aafc/dina/search/messaging/producer/RabbitMQMessageProducer.java
MessageProducer is now interface
> 23683 MessageProducer should be interface

- search-ws/README.md
update parameter and index names
> 24578_update_documentation_for_ws_requests

- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/indexing/DinaIndexDocumentIT.java
using BeforeAll and AfterAll, we will start and stop the container once
> 24745_improve_test_runtime

- README.md
- local/docker-compose.yml.example
- pom.xml
- spotbugs-exclude.xml
Updated ElasticSearch, log4j2, SpotBugs and dependency-check
> 26052 Update ElasticSearch to 7.16.2

- pom.xml
- search-cli/src/main/resources/log4j2.yaml
- search-ws/src/main/resources/log4j2.yaml
Fixed logging configuration and added config file
> 26100 Add logging configuration

- pom.xml
Updated SpringBoot, log4j2 and dependency-check
> 26120 Update dependencies

- search-ws/README.md
- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/controller/SearchController.java
renamed endpoints and refresh README
> 26443 Rename text endpoint

- search-ws/src/main/resources/mappings.yml
> 27009 Expand collecting-event and organism mapping config file

- pom.xml
- search-cli/src/main/resources/endpoints.yml
- search-messaging/pom.xml
- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/services/ESSearchService.java
- search-ws/src/main/resources/mappings.yml
Added configuration and removed unnecessary code
> 27395 Add preparationType to search-cli and search-ws

- search-ws/README.md
- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/services/AutocompleteResponse.java
- search-ws/src/test/java/ca/gc/aafc/dina/search/ws/search/DinaSearchDocumentIT.java
Added documentId to the autocomplete response
> Return id of document in autocomplete

- search-cli/src/main/resources/endpoints.yml
added derivatives to metadata relationships on search-cli
> 27995 Add derivative to metadata index

- local/.env
- local/elastic-configurator-settings/dina_storage_index_settings.json
- search-cli/src/main/resources/endpoints.yml
- search-ws/src/main/resources/mappings.yml
Allow autocomplete on storage-unit name + fixed default config for storage-unit indexing
> 28041 Update storage index mapping

- search-ws/README.md
- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/controller/SearchController.java
- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/services/ESSearchService.java
- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/services/SearchService.java
- search-ws/src/test/java/ca/gc/aafc/dina/search/ws/search/DinaSearchDocumentIT.java
Added group as a parameter to auto-complete so it can be used to filter results
> 28156 Add group to auto-complete

- local/elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
Changed mapping to allow autocomplete on some nested fields
> 28163 Add search_as_you_type for verbatim agents

- search-cli/src/main/resources/endpoints.yml
- search-ws/src/main/resources/mappings.yml
Added search-ws mapping config and relationship for search-cli
> 28218 Update mapping for PreparationMethod

- local/elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
Added preparation-method relationship to mapping
> 28244 PreparationMethod missing from mat-sample mapping

- local/elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
- search-cli/src/main/resources/endpoints.yml
- search-ws/src/main/resources/mappings.yml
Updated mapping and config files
> 28394 Add assemblage relationship to mat-sample mapping

- search-ws/src/main/resources/mappings.yml
collection code and name ar now set as distinctTermAgg
> Support #28546 - Set collection as distinctTermAgg

- local/docker-compose.yml.example
- local/elasticsearch/Dockerfile
- pom.xml
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/containers/DinaElasticSearchContainer.java
- search-ws/src/test/java/ca/gc/aafc/dina/search/ws/container/DinaElasticSearchContainer.java
- search-ws/src/test/java/ca/gc/aafc/dina/search/ws/search/SearchWithICUPluginIT.java
- search-ws/src/test/resources/Dockerfile
Updated ElasticSearch and added a test to prove that the mapping is now working with the ICU plugin enabled
> 28590 Update to ElasticSearch 7.17.6

- local/elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
- pom.xml
- search-cli/src/main/resources/endpoints.yml
- search-ws/src/main/resources/mappings.yml
Added projects to material-sample mapping, host and managed-attributes
> 28630 Add more search-ws mapping options

- es-init-container/create-index.sh
Add a command to print the es mapping before sending it (for debug purpose)
> 28746 Add more output to es-init-container

- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/controller/SearchController.java
- search-ws/src/test/java/ca/gc/aafc/dina/search/ws/search/SearchControllerIT.java
Fixed regex and added test for the web layer
> 29439 Autocomplete paths not passing regex since it contains periods

- local/README.md
- local/elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/indexing/DinaIndexDocumentIT.java
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/messaging/DocumentProcessorEmbeddedIT.java
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/utils/ElasticSearchTestUtils.java
- search-cli/src/test/resources/elastic-configurator-settings/agent-index/dina_agent_index_settings.json
Added test to check date_detection behavior
> 29427 Improve index mapping

- local/elastic-configurator-settings/object-store-index/object_store_index_settings.json
> 29580 Add more keyword fields to object-store mapping

- search-ws/src/main/resources/mappings.yml
- search-ws/src/test/resources/es-mapping/material_sample_index_settings.json
- search-ws/src/test/resources/test-documents/material_sample_dynamic_fields_document.json
Added more search option for restrictions and verbatimlocality
> 29993_Add_search_mapping_for_restrictions_and_geo_assertion

- local/elastic-configurator-settings/dina_loan_transaction_index_settings.json
- Added nested materialSamples mapping to loan transaction index settings
> 30378 Loan Transaction index add explicit mapping

- local/docker-compose.yml.example
- local/elasticsearch/Dockerfile
- pom.xml
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/containers/DinaElasticSearchContainer.java
- search-ws/src/test/java/ca/gc/aafc/dina/search/ws/container/DinaElasticSearchContainer.java
- search-ws/src/test/resources/Dockerfile
Updated ElasticSearch to 7.17.10 including test base images
> 30954 Update ElasticSearch to 7.17.10

- search-ws/src/main/resources/mappings.yml
> 31924 Add more object-store fields to search-ws

- local/elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
- search-ws/src/main/resources/mappings.yml
Added more default filters and removed bucket since it was causing confusion in the UI
> 32091 Update default config for filters

- search-messaging/pom.xml
exclude spring-jpa-starter from dina-messaging
> 32692 search-cli 0.28 not starting

- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/config/MessageProcessorTestConfiguration.java
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/messaging/DinaMessageProducerConsumerIT.java
- search-cli/src/test/java/ca/gc/aafc/dina/search/cli/messaging/LatchBasedMessageProcessor.java
Changed test to use latch instead of wait()
> 32750 Rewrite flaky test in DinaMessageProducerConsumerIT

- search-ws/src/main/java/ca/gc/aafc/dina/search/ws/services/ESSearchService.java
- search-ws/src/main/resources/mappings.yml
- Added subtypes for each date in the mapping.
- Subtype is now provided in the handleRelationshipSection function
> Support #33360 - Updating mapping yml to include dateSubtypes for dates

- search-ws/src/main/resources/mappings.yml
Added new field to mappings.yml
> 33719 Add new scientificName calculated field

- search-ws/src/main/resources/mappings.yml
Added identifiers and missing preparation related attributes to mapping
> 34596 Add material-sample identifiers mapping

- search-cli/src/main/java/ca/gc/aafc/dina/search/cli/config/IndexSettingDescriptor.java
- search-cli/src/main/java/ca/gc/aafc/dina/search/cli/indexing/DocumentManager.java
Added reverse relationship support to reindex embedded
> 35961 Add reverse rel support to getIndexForRelationshipType

- es-init-container/es_functions.sh
> Support #36020 - Add error messages for reindex function

- es-init-container/es_functions.sh
Removed bc (basic calculator) command since it is not required anymore
> 36256 Remove usage of basic calculator for schema version

- local/elastic-configurator-settings/dina_project_index_settings.json
- search-ws/src/main/resources/mappings.yml
- Updated mappings to add more fields.
- Updated the index settings to include the attachment relationship.
> Support #36366 - Add project fields to the index mapping
